{{- if and .Values.ExternalSecret.enabled (eq .Values.ExternalSecret.type "hashicorp") }}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ include "deployment.fullname" . }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: {{ .Values.ExternalSecret.name }}
    kind: SecretStore
  target:
    name: {{ include "deployment.fullname" . }}
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
{{- range .Values.ExternalSecret.kvPath }}
  - key: {{ . }}
    metadataPolicy: None
    decodingStrategy: None
    conversionStrategy: Default
{{- end }}
{{- end }}