{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "deployment.fullname" . }}
  labels:
    {{- include "deployment.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      protocol: {{ .protocol }}
      targetPort: {{ .port }}
      name: {{ .name }}
    {{- end }}          
  selector:
    {{- include "deployment.selectorLabels" . | nindent 4 }}
{{- end }}